name: 🔒 Security Report
description: Report a security vulnerability
title: "[SECURITY]: "
labels: ["security", "high-priority"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: Please do not report security vulnerabilities in public issues.
        
        For security vulnerabilities, please email: security@sew4mi.com
        
        This form is for non-sensitive security improvements and hardening suggestions only.

  - type: dropdown
    id: type
    attributes:
      label: Security Issue Type
      description: What type of security improvement are you suggesting?
      options:
        - Security Enhancement (non-vulnerable)
        - Dependency Security Update
        - Security Configuration Improvement
        - Security Documentation
        - Security Testing Improvement
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security improvement you're suggesting
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: What security benefit would this provide?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you suggest we implement this security improvement?

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This is NOT a vulnerability report (vulnerabilities should be reported privately)
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true